services:
  postgres_data:
    container_name: postgres_data_container
    image: postgres:14.8-alpine3.18
    command:
      - "postgres"
      - "-c"
      - "max_connections=50"
      - "-c"
      - "shared_buffers=1GB"
      - "-c"
      - "effective_cache_size=4GB"
      - "-c"
      - "work_mem=16MB"
      - "-c"
      - "maintenance_work_mem=512MB"
      - "-c"
      - "random_page_cost=1.1"
      - "-c"
      - "temp_file_limit=10GB"
      - "-c"
      - "log_min_duration_statement=200ms"
      - "-c"
      - "idle_in_transaction_session_timeout=10s"
      - "-c"
      - "lock_timeout=1s"
      - "-c"
      - "statement_timeout=60s"
      - "-c"
      - "shared_preload_libraries=pg_stat_statements"
      - "-c"
      - "pg_stat_statements.max=10000"
      - "-c"
      - "pg_stat_statements.track=all"
    environment:
      POSTGRES_DB: "plantsdb"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "123Secret_a"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ../2. Init Database:/docker-entrypoint-initdb.d
      - plants-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d plantsdb"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
    networks:
      - postgres
      - backend

  postgres_identity:
    container_name: postgres_identity_container
    image: postgres:14.8-alpine3.18
    command:
      - "postgres"
      - "-c"
      - "max_connections=50"
      - "-c"
      - "shared_buffers=1GB"
      - "-c"
      - "effective_cache_size=4GB"
      - "-c"
      - "work_mem=16MB"
      - "-c"
      - "maintenance_work_mem=512MB"
      - "-c"
      - "random_page_cost=1.1"
      - "-c"
      - "temp_file_limit=10GB"
      - "-c"
      - "log_min_duration_statement=200ms"
      - "-c"
      - "idle_in_transaction_session_timeout=10s"
      - "-c"
      - "lock_timeout=1s"
      - "-c"
      - "statement_timeout=60s"
      - "-c"
      - "shared_preload_libraries=pg_stat_statements"
      - "-c"
      - "pg_stat_statements.max=10000"
      - "-c"
      - "pg_stat_statements.track=all"
    environment:
      POSTGRES_DB: "identitydb"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "123Secret_a"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ../2. Init Database:/docker-entrypoint-initdb.d
      - identity-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d identitydb"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
    networks:
      - postgres
      - backend

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:7.2
    environment:
      PGADMIN_DEFAULT_EMAIL: "plantsuser@plants.com"
      PGADMIN_DEFAULT_PASSWORD: "123Secret_a"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - "5050:80"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
    networks:
      - postgres    

  plantschedulerapi:
    container_name: plant-scheduler-api
    image: ${DOCKER_REGISTRY-}plantschedulerapi
    build:
      context: .
      dockerfile: src/PlantSchedulerAPI/Dockerfile
    environment:
      - DB_HOST=postgres_data
      - POSTGRES_DB=plantsdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123Secret_a
    depends_on:
        postgres_data:
            condition: service_healthy
            restart: true
    ports:
      - "8088:8080"
    networks:
      - backend
    healthcheck:
      test: curl --fail http://localhost:8080/health || exit 1
      interval: 2s
      timeout: 5s
      retries: 3
      start_period: 5s

  authapi:
    container_name: auth-api
    image: ${DOCKER_REGISTRY-}authapi
    build:
      context: .
      dockerfile: src/AuthAPI/Dockerfile
    environment:
      - DB_HOST=postgres_identity
      - POSTGRES_DB=identitydb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123Secret_a
    depends_on:
      postgres_identity:
        condition: service_healthy
        restart: true
    networks:
      - backend
    healthcheck:
      test: curl --fail http://localhost:8080/health || exit 1
      interval: 2s
      timeout: 5s
      retries: 3
      start_period: 5s

  recognizeapi:
    container_name: recognize-api
    build:
      context: .
      dockerfile: src/RecognizeAPI/Dockerfile
    ports:
      - "8888:80"
    networks:
      - backend
    healthcheck:
      test: curl --fail http://localhost:80/health || exit 1
      interval: 2s
      timeout: 5s
      retries: 3
      start_period: 5s

  apigateway:
    container_name: api-gateway
    image: ${DOCKER_REGISTRY-}apigateway
    build:
      context: .
      dockerfile: src/ApiGateway/Dockerfile
    ports:
      - "8081:8080"
    networks:
      - backend
      - gate
    healthcheck:
      test: curl --fail http://localhost:8080/healthz || exit 1
      interval: 2s
      timeout: 5s
      retries: 3
      start_period: 5s
      


volumes:
  identity-data:
  plants-data:
  pgadmin-data:

networks:
  postgres:
    driver: bridge
  gate:
    driver: bridge
  backend:
    driver: bridge
    



