
name: .NET

on:
  push:
    paths:
    - 'MyGarden/src/**'
    - 'MyGarden/tests/GradenAPI.Tests'
    - 'MyGarden/**'
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]    

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Get code from repository
      uses: actions/checkout@v4
      with:
        ref: main
    - name: Make the script files executable
      run: | 
        cd MyGarden
        chmod +x healthcheck.sh 
    - name: Run tests
      run: dotnet test MyGarden/tests/*.Tests/*.csproj

    - name: Build and push docker containers
      run: |
        cd MyGarden
        docker compose up -d > build_logs.txt  
    - name: Upload build logs as artifact
      uses: actions/upload-artifact@v3
      with:
        name: build-logs
        path: MyGarden/build_logs.txt  

    - name: Healthcheck containers
      run: | 
        cd MyGarden
        ./healthcheck.sh postgres_data_container 120
        ./healthcheck.sh garden-api 120 
        ./healthcheck.sh auth-api 120 
        ./healthcheck.sh recognize-api 120 
        ./healthcheck.sh api-gateway 120 

