
name: .NET

on:
  push:
    paths:
    - 'MyGarden/src/**'
    - 'MyGarden/tests/GradenAPI.Tests'
    - 'MyGarden/**'
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]    

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Get code from repository
      uses: actions/checkout@v4
      with:
        ref: main

    
    - name: Healthcheck containers
      run: | 
        ls -a
        healthcheck.sh postgres_data_container 120
        healthcheck.sh garden-api 120 
        healthcheck.sh auth-api 120 
        healthcheck.sh recognize-api 120 
        healthcheck.sh api-gateway 120 

